import { useState } from 'react'
import { useT } from '../ctx.jsx'
import { API, post } from '../api.js'
import { useFetchOnce } from '../hooks.js'
import { Badge, Btn, Card, Empty, Modal, Input } from '../components/ui.jsx'
export default function Scheduler({toast}){const{C,sz}=useT();const{data,loading,reload}=useFetchOnce(`${API}/crontab`);const[showAdd,setShowAdd]=useState(false);const[newJob,setNewJob]=useState({cron:'',command:'',comment:''})
  const addJob=async()=>{if(!newJob.cron||!newJob.command){toast('Cron+command required','danger');return};const r=await post(`${API}/crontab/add`,newJob);if(r.error){toast(r.error,'danger');return};toast(r.message||'Added');setShowAdd(false);setNewJob({cron:'',command:'',comment:''});reload()}
  const removeJob=async raw=>{const r=await post(`${API}/crontab/remove`,{raw});if(r.error){toast(r.error,'danger');return};toast('Removed','warning');reload()}
  const presets=[{label:'Daily Restart 4AM',cron:'0 4 * * *',cmd:'sudo systemctl restart arma-reforger'},{label:'Update Check 6hr',cron:'0 */6 * * *',cmd:'/usr/games/steamcmd +force_install_dir /opt/arma-server +login anonymous +app_update 1874900 validate +quit'},{label:'Log Cleanup 3AM',cron:'0 3 * * *',cmd:'find /opt/arma-server/profile/logs -name "*.log" -mtime +7 -delete'},{label:'Weekly Restart Sun 5AM',cron:'0 5 * * 0',cmd:'sudo systemctl restart arma-reforger'}]
  if(loading)return <div className="animate-pulse" style={{color:C.textDim,fontSize:sz.base}}>Loading...</div>;const jobs=data?.jobs||[]
  return <div><div className="flex items-center gap-3 mb-4 flex-wrap"><h2 className="font-black" style={{color:C.textBright,fontSize:sz.base+4}}>Scheduler</h2><Badge text={`${jobs.length} active`}/><div className="flex-1"/><Btn onClick={()=>setShowAdd(true)}>+ Add</Btn></div>
    {jobs.length===0?<Empty title="No cron jobs" sub="Add scheduled tasks"/>:<div className="space-y-1.5 mb-4">{jobs.map((j,i)=><Card key={i} className="px-5 py-3 flex items-center gap-3"><div className="w-2.5 h-2.5 rounded-full" style={{background:C.accent}}/><div className="flex-1 min-w-0"><div className="font-mono font-bold truncate" style={{color:C.text,fontSize:sz.base}}>{j.command}</div><div className="flex items-center gap-2 mt-0.5"><span className="font-mono px-2 py-0.5 rounded" style={{background:C.accentBg,color:C.accent,fontSize:sz.stat}}>{j.cron}</span>{j.comment&&<span style={{color:C.textMuted,fontSize:sz.stat}}>{j.comment}</span>}</div></div><Btn small v="danger" onClick={()=>removeJob(j.raw)}>X</Btn></Card>)}</div>}
    <Card className="p-5 mt-4"><div className="font-black uppercase tracking-wide mb-3" style={{color:C.textDim,fontSize:sz.label}}>Quick Add</div><div className="flex gap-2 flex-wrap">{presets.map((p,i)=>{const exists=jobs.some(j=>j.cron===p.cron);return <Btn key={i} small v={exists?'dim':'ghost'} disabled={exists} onClick={async()=>{const r=await post(`${API}/crontab/add`,{cron:p.cron,command:p.cmd,comment:p.label});if(r.error)toast(r.error,'danger');else{toast(`Added ${p.label}`);reload()}}}>{exists?'OK ':'+ '}{p.label}</Btn>})}</div></Card>
    {data?.raw&&<Card className="p-5 mt-3"><div className="font-black uppercase tracking-wide mb-2" style={{color:C.textDim,fontSize:sz.label}}>Raw</div><pre className="rounded-lg p-3 font-mono overflow-auto" style={{background:C.consoleBg,color:C.textDim,fontSize:sz.code,lineHeight:'1.9'}}>{data.raw}</pre></Card>}
    <Modal open={showAdd} onClose={()=>setShowAdd(false)} title="Add Cron Job"><Input label="Schedule" value={newJob.cron} onChange={v=>setNewJob(p=>({...p,cron:v}))} placeholder="*/5 * * * *" mono/><Input label="Command" value={newJob.command} onChange={v=>setNewJob(p=>({...p,command:v}))} placeholder="sudo systemctl restart arma-reforger" mono/><Input label="Comment" value={newJob.comment} onChange={v=>setNewJob(p=>({...p,comment:v}))} placeholder="Daily restart"/><div className="mb-3" style={{color:C.textMuted,fontSize:sz.stat}}>Format: minute hour day month weekday</div><div className="flex gap-2 justify-end"><Btn v="ghost" onClick={()=>setShowAdd(false)}>Cancel</Btn><Btn onClick={addJob}>Add</Btn></div></Modal></div>}

