import { useState, useEffect } from 'react'
import { useT } from '../ctx.jsx'
import { API, put, post } from '../api.js'
import { useFetchOnce } from '../hooks.js'
import { Badge, Btn, Card, Toggle, Input } from '../components/ui.jsx'

export default function Webhooks({toast}){const{C,sz}=useT();const{data:initial,reload}=useFetchOnce(`${API}/webhooks`);const[hooks,setHooks]=useState(null);const[editing,setEditing]=useState(null);useEffect(()=>{if(initial&&!hooks)setHooks(initial)},[initial]);const update=(id,field,val)=>setHooks(p=>p.map(h=>h.id===id?{...h,[field]:val}:h));const saveAll=async()=>{const r=await put(`${API}/webhooks`,hooks);r.error?toast(r.error,'danger'):toast('Saved')};const testHook=async url=>{if(!url){toast('Set URL','danger');return};const r=await post(`${API}/webhooks/test`,{url});r.error?toast(r.error,'danger'):toast('Sent!')}
  if(!hooks)return <div className="animate-pulse" style={{color:C.textDim}}>Loading...</div>
  return <div><div className="flex items-center gap-3 mb-4 flex-wrap"><h2 className="font-black" style={{color:C.textBright,fontSize:sz.base+4}}>Webhooks</h2><Badge text={`${hooks.filter(h=>h.enabled&&h.url).length} active`}/><div className="flex-1"/><Btn v="ghost" onClick={()=>setHooks(p=>[...p,{id:Date.now(),name:'New',url:'',events:[],enabled:false}])}>+ Add</Btn><Btn onClick={saveAll}>Save</Btn></div><div className="space-y-2">{hooks.map(h=><Card key={h.id} className="p-4"><div className="flex items-center gap-3 mb-2"><Toggle value={h.enabled} onChange={()=>update(h.id,'enabled',!h.enabled)}/><div className="flex-1"><div className="font-bold" style={{color:C.text,fontSize:sz.base+1}}>{h.name}</div></div><Btn small v="ghost" onClick={()=>setEditing(editing===h.id?null:h.id)}>{editing===h.id?'Close':'Edit'}</Btn><Btn small v="danger" onClick={()=>setHooks(p=>p.filter(x=>x.id!==h.id))}>X</Btn></div>{editing===h.id&&<div className="pt-3 mt-2 space-y-3" style={{borderTop:`1px solid ${C.border}`}}><Input label="Name" value={h.name} onChange={v=>update(h.id,'name',v)}/><Input label="Discord URL" value={h.url} onChange={v=>update(h.id,'url',v)} placeholder="https://discord.com/api/webhooks/..." mono/><div><label className="block font-bold uppercase tracking-wide mb-2" style={{color:C.textDim,fontSize:sz.label}}>Events</label><div className="flex gap-1.5 flex-wrap">{['connect','disconnect','kick','ban','kill','chat','start','stop','crash'].map(ev=><button key={ev} onClick={()=>update(h.id,'events',h.events.includes(ev)?h.events.filter(x=>x!==ev):[...h.events,ev])} className="px-2.5 py-1 rounded font-bold cursor-pointer" style={{background:h.events.includes(ev)?C.accentBg:'transparent',color:h.events.includes(ev)?C.accent:C.textMuted,border:`1px solid ${h.events.includes(ev)?C.accent+'30':C.border}`,fontSize:sz.stat}}>{ev}</button>)}</div></div><Btn v="info" onClick={()=>testHook(h.url)}>Test</Btn></div>}{editing!==h.id&&h.url&&<div className="font-mono truncate" style={{color:C.textMuted,fontSize:sz.stat}}>{h.url}</div>}</Card>)}</div></div>}
